name: fintech_app
description: ""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - 'assets/drums.mp3'
    - 'assets/onboarding.png'